# Generated by Django 2.1.2 on 2018-11-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('load_csv', '0002_auto_20181031_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceNeighbors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor', to='load_csv.Province')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load_csv.Province')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='provinceneighbors',
            unique_together={('province', 'neighbor')},
        ),
    ]
