# Generated by Django 2.1.2 on 2018-11-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceneighbors',
            name='neighbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor', to='load_csv.Province'),
        ),
    ]
