# Generated by Django 2.1.2 on 2018-10-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_csv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='luas',
            new_name='area',
        ),
    ]
